### ISSUE TITLE
Random weird flash on my screen whenever in the Maw

### ISSUE THREAD

**Issue by deikun** [Dathwada/handynotes-oribos#4]
![image](https://user-images.githubusercontent.com/20842964/102018722-a756a800-3d34-11eb-8968-48034a480d1e.png)
![image](https://user-images.githubusercontent.com/20842964/102018714-99a12280-3d34-11eb-9125-bfd458c1ec60.png)

At first I thought I was going crazy, but after noticing it many times I decided to record it to see what it was. It flashes on the screen for just a milisecond. I think it may be related to the waypoint setting option I turned on. I did have a WA installed that did the same feature but I removed it after I noticed you added it to this HN plugin. I'm going to try testing it out with it off and on and see if it persists.

**Comment by Dathwada** [comment]
A Cursforge user reported this already and this is fixed in the next release.

**Comment by deikun** [comment]
Whoops, my apologies for not checking prior issues. I'll go ahead and close this. Thank you for the prompt response! 🙏🏼

**Comment by Dathwada** [comment]
Version 8 is now available on Curseforge.
