### ISSUE TITLE
Add Icon for the Korthia-Portal

### ISSUE THREAD

**Issue by gitarrg-org** [Dathwada/handynotes-oribos#5]
Hey there,

might be nice to add a small little icon on the Ring of Transference to indicate the position of the portal to Korthia
![image](https://user-images.githubusercontent.com/82116652/124112848-a6802c00-da62-11eb-82bd-b7db19789aca.png)

**Comment by Dathwada** [comment]
It'll come in the next update. I haven't played on the PTR and wasn't aware that there is this new "portal".

**Comment by Dathwada** [comment]
Added in v13.
