### ISSUE TITLE
Bugsack error

### ISSUE THREAD

**Issue by addonaddict** [Dathwada/handynotes-oribos#6]
1x HandyNotes_Oribos\core\handler.lua:449: attempt to concatenate a nil value
[string "@HandyNotes_Oribos\core\handler.lua"]:449: in function `?'
[string "@HandyNotes_Oribos\core\handler.lua"]:482: in function <HandyNotes_Oribos\core\handler.lua:481>

Locals:
self = <unnamed> {
 0 = <userdata>
}
(*temporary) = <function> defined @HandyNotes_Oribos\core\dev.lua:54
(*temporary) = <table> {
 SetDefaultModuleLibraries = <function> defined @Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:367
 description = "Displays the NPC and POI locations in Oribos on the world map and minimap."
 Enable = <function> defined @Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:294
 UnregisterAllEvents = <function> defined @AllTheThings\lib\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 EnableModule = <function> defined @Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:332
 modules = <table> {
 }
 GetModule = <function> defined @Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:210
 IterateEmbeds = <function> defined @Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:442
 defaultModuleLibraries = <table> {
 }
 TimeLeft = <function> defined @Details\Libs\AceTimer-3.0\AceTimer-3.0.lua:172
 ScheduleRepeatingTimer = <function> defined @Details\Libs\AceTimer-3.0\AceTimer-3.0.lua:129
 CancelAllTimers = <function> defined @Details\Libs\AceTimer-3.0\AceTimer-3.0.lua:160
 SetDefaultModulePrototype = <function> defined @Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:409
 name = "HandyNotes_Oribos"
 IsEnabled = <function> defined @Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:451
 orderedModules = <table> {
 }
 ScheduleTimer = <function> defined @Details\Libs\AceTimer-3.0\AceTimer-3.0.lua:94
 DisableModule = <function> defined @Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:350
 RegisterMessage = <function> defined @AllTheThings\lib\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @AllTheThings\lib\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 constants = <table> {
 }
 CharacterHasProfession = <function> defined @HandyNotes_Oribos\core\handler.lua:45
 IsModule = <function> defined @Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:468
 db = <table> {
 }
 SendMessage = <function> defined @AllTheThings\lib\CallbackHandler-1.0\CallbackHandler-1.0.lua:59
 baseName = "HandyNotes_Oribos"
 debugmsg = <function> defined @HandyNotes_Oribos\core\dev.lua:54
 SetEnabledState = <function> defined @Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:424
 NewModule = <function> defined @Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:235
 enabledState = true
 OnEnable = <function> defined @HandyNotes_Oribos\core\handler.lua:432
 RegisterEvent = <function> defined @AllTheThings\lib\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterAllMessages = <function> defined @AllTheThings\lib\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 Refresh = <function> defined @HandyNotes_Oribos\core\handler.lua:428
 OnInitialize = <function> defined @HandyNotes_Oribos\core\handler.lua:409
 CancelTimer = <function> defined @Details\Libs\AceTimer-3.0\AceTimer-3.0.lua:147
 IterateModules = <function> defined @Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:437
 pluginName = "Oribos"
 SetDefaultModuleState = <function> defined @Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:387
 GetName = <function> defined @Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:279
 defaultModuleState = true
 UnregisterEvent = <function> defined @AllTheThings\lib\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 Disable = <function> defined @Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:314
}
(*temporary) = "MapID: "
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to concatenate a nil value"
addon = <table> {
 SetDefaultModuleLibraries = <function> defined @Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:367
 description =

**Comment by Dathwada** [comment]
Do you have dev mode enabled?
And I assume you were in Oribos when the Lua error occurred?

**Comment by addonaddict** [comment]
No devmode enabled
I entered ice crown area, the first quest that starts shadowlands expansion. And got that error
________________________________
